/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mugModel.glb
Author: Nick Scott (https://sketchfab.com/Nickjjscott)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/crusader-mug-3066dc0d8f1c48a49c415caf769924a5
Title: Crusader Mug
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function MugModel(props) {
  const { nodes, materials } = useGLTF("/mugModel.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.SM_CrusaderMug_M_Checker_0.geometry}
        material={materials.Checker}
      />
    </group>
  );
}

useGLTF.preload("/mugModel.glb");
