/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ps5Model.glb
Author: rtql8d (https://sketchfab.com/rtql8d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ps5-box-disc-eafd8388e1b84e9bb36c21d66b22c57d
Title: PS5 Box (Disc)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function ConsoleModel(props) {
  const { nodes, materials } = useGLTF("/ps5Model.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.Acrylic_Clear}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.Paper_White}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.Paper_White_NONE}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/ps5Model.glb");
